image: docker:latest  

services:
  - docker:dind  

variables:
  IMAGE_NAME: "$CI_REGISTRY_IMAGE"  
  IMAGE_TAG: "$CI_COMMIT_SHORT_SHA"  

stages:
  - build
  - push

image-build:
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY" 
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .  
  after_script:
    - docker push $IMAGE_NAME:$IMAGE_TAG  

