apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chainsaw-tests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://gitlab.com/smart-ict-group2/argocd-chainsaw-validation-hooks.git'
    targetRevision: Lamiae
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
